[syntalos_module]
type = "python"

name = "LED Controller"
description = "Controls a Firmata device. Makes the Firmata device send pulses on two digital output pins. These outputs should be connected to digital inputs of an Arduino capable of generating periodic LED pulses. The LED pulses are intended for launch sync or marathon experiments to quantify time drifts and delays."
icon = "led.svg"

main = "mod-main.py"
use_venv = false

# By default development modules don't show up in Syntalos
# unless you activate the developer mode.
devel = false

# This will put it inside the "Device Support" group in the "Add Module" GUI
categories = 'device'
features = ['show-settings']

[ports]

[[ports.out]]
data_type = 'IntSignalBlock'
id = 'start_pulse'
signal_names = ['START_PULSE']
title = 'Start pulse'

[[ports.out]]
data_type = 'FirmataControl'
id = 'firmatactl'
title = 'Firmata control'
